version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kk_bot
    restart: unless-stopped
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    networks:
      - telegram-bot-network
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  telegram-bot-network:
    driver: bridge
